# アクション名
name: CI

# タイミングを指定
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "frontend/**"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 
      - name: yarn install
        run: yarn install
        working-directory: ./frontend
      - name: Run eslint
        run: yarn lint
        working-directory: ./frontend
      - name: Run Jest
        run: yarn jest
        working-directory: ./frontend
